-- 1. PROFILES TABLE (Extends Auth Users)
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  name text,
  email text,
  role text check (role in ('donor', 'hospital', 'admin')) default 'donor',
  blood_group text,
  age integer,
  phone text,
  address text
);

-- 2. BLOOD STOCK TABLE
create table blood_stock (
  id bigint generated by default as identity primary key,
  group_name text unique not null,
  quantity integer default 0,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. DONATION REQUESTS TABLE
create table donation_requests (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  patient_name text,
  blood_group text,
  units integer,
  hospital_name text,
  status text check (status in ('pending', 'approved', 'fulfilled', 'rejected')) default 'pending',
  requester_id uuid references profiles(id)
);

-- RLS POLICIES (Security)
alter table profiles enable row level security;
alter table blood_stock enable row level security;
alter table donation_requests enable row level security;

-- Profiles: Public Read, Auth Insert/Update Own
create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profile." on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);

-- Blood Stock: Everyone Read, Only Admin/Hospital Update
create policy "Blood stock viewable by everyone" on blood_stock for select using (true);
create policy "Admin and Hospital can update stock" on blood_stock for update using (
  exists (select 1 from profiles where id = auth.uid() and role in ('admin', 'hospital'))
);

-- Requests: Everyone Read, Auth Create, Admin/Hospital Update Status
create policy "Requests viewable by everyone" on donation_requests for select using (true);
create policy "Authenticated users can create requests" on donation_requests for insert with check (auth.role() = 'authenticated');
create policy "Admin/Hospital can update requests" on donation_requests for update using (
    exists (select 1 from profiles where id = auth.uid() and role in ('admin', 'hospital'))
);

-- SAMPLE DATA INSERTION (Run this to populate DB)
-- Note: You can't insert directly into 'auth.users' via SQL here efficiently without admin connection.
-- Instead, we seed the BLOOD STOCK table.
insert into blood_stock (group_name, quantity) values
('A+', 15), ('A-', 5), 
('B+', 20), ('B-', 4), 
('AB+', 8), ('AB-', 2), 
('O+', 30), ('O-', 10)
on conflict (group_name) do nothing;

-- TRIGGER: Auto-create profile on signup (Optional but recommended)
-- This ensures every auth user has a profile row.
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, name, role, blood_group, age, phone)
  values (
      new.id, 
      new.email, 
      new.raw_user_meta_data->>'name', 
      COALESCE(new.raw_user_meta_data->>'role', 'donor'),
      new.raw_user_meta_data->>'blood_group',
      (new.raw_user_meta_data->>'age')::int,
      new.raw_user_meta_data->>'phone'
  );
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
